### ISSUE TITLE
Kortsiktige mål?

### ISSUE THREAD

**Issue by Jaknil** [robotikklinja/KUKA-KR-6-R700#3]
Bra at dere skrevet mål, jeg rekommanderer dere å formulere noe konkrete kortsiktige mål og sette dem i rekkefølge, altså svare på spørsmålet, hva skall til nå for å jobbe mot målet? Kanskje må dere lage en dør eller bli kjent med noen software. Da finner dere kanskje ut at dere trenger noe mer utstyr, så kan vi bestille det innen dere sitter fast og venter på det :)

**Comment by kubenkodeklubb** [comment]
Vi har allerede funnet ut hva som må bestilles og hovedprioriteten er å sette opp sikkerheten på roboten før noe annet. Vi må snakke med James og se hva han tenker rundt de andre ting som må gjøres med dette prosjektet. Du kan gå inn på "Projects" fanen og se på roadmappen for å se hva som er planlagt å gjøre.
